# Generated by Django 2.1.8 on 2020-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
