# Generated by Django 2.1.8 on 2020-05-14 13:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20200514_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
