# Generated by Django 2.1.8 on 2020-06-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20200514_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'ordering': ['-click_nums']},
        ),
    ]
